//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adelante.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccessDetail
    {
        public int Id { get; set; }
        public Nullable<int> ClientAccessId { get; set; }
        public string GuessName { get; set; }
        public Nullable<bool> Confirmed { get; set; }
    
        public virtual ClientAccess ClientAccess { get; set; }
    }
}
