//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adelante.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAccess()
        {
            this.ClientAccessDetails = new HashSet<ClientAccessDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActiveNeighborhoodId { get; set; }
        public Nullable<int> ClientAdressesId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ActiveNeighborhood ActiveNeighborhood { get; set; }
        public virtual ClientAddress ClientAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAccessDetail> ClientAccessDetails { get; set; }
    }
}
