//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adelante.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNeighborhood
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ActiveNeighborhoodId { get; set; }
    
        public virtual ActiveNeighborhood ActiveNeighborhood { get; set; }
        public virtual Client Client { get; set; }
    }
}
