//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adelante.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighborhood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Neighborhood()
        {
            this.ActiveNeighborhoods = new HashSet<ActiveNeighborhood>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Clave { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PostalCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveNeighborhood> ActiveNeighborhoods { get; set; }
        public virtual City City { get; set; }
    }
}
