//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adelante.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Accesos {
            get {
                return ((string)(this["Accesos"]));
            }
            set {
                this["Accesos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IB4LJSG\\SQLEXPRESS;Initial Catalog=SensaLaserDB;Persist Secur" +
            "ity Info=True;User ID=sa;Password=sql3adm8")]
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
            set {
                this["Conexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sesion {
            get {
                return ((bool)(this["Sesion"]));
            }
            set {
                this["Sesion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pc\\sqlexpress;Initial Catalog=SensaLaserDB;Persist Security Info=True" +
            ";User ID=sa;Password=sensa2133!!!!!!!")]
        public string SensaLaserDBConnectionString {
            get {
                return ((string)(this["SensaLaserDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IB4LJSG\\SQLEXPRESS;Initial Catalog=dbAdelante;Persist Securit" +
            "y Info=True;User ID=sa;Password=sql3adm8;MultipleActiveResultSets=True;Applicati" +
            "on Name=EntityFramework")]
        public string dbAdelanteConnectionString {
            get {
                return ((string)(this["dbAdelanteConnectionString"]));
            }
        }
    }
}
